services:
  - type: web
    name: servicio-reparacion-pc
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.18.1
    healthCheckPath: /api/health
    autoDeploy: true
